### PR TITLE
Explicitly say upper bit in GPR is undefined when passing floating po…

### LINKED ISSUE #267: More clarification for passing floating point value on GPR
Review comment come from @anderslindgren-iar and Anders Berg(IAR) https://lists.riscv.org/g/tech-toolchain-runtime/message/344

> without extending the integer to XLEN bits,

Anders: This may need an additional clarification. If the higher bits are regarded as undefined, it should be clear it is so.

### PR DESCRIPTION
**Pull request by kito-cheng**
…int value in hard fp CC.

Fix #267.

### CODE REVIEW

**Review by aswaterman — COMMENTED** [review]
This sentence is already very long.  May I suggest breaking it up?  Here's my attempt:

A struct containing one floating-point real and one integer (or bitfield), in
either order, is passed in a floating-point register and an integer register,
provided the floating-point real is no more than FLEN bits wide and the
integer is no more than XLEN bits wide, and at least one floating-point
argument register and at least one integer argument register is available.
If the struct is passed in this manner, and the integer is narrower than XLEN
bits, the remaining bits are unspecified.
If the struct is not passed in this manner, then it is passed according to the
integer calling convention.

**Comment by jrtc27** [comment]
> This sentence is already very long. May I suggest breaking it up? Here's my attempt:
> 
> A struct containing one floating-point real and one integer (or bitfield), in either order, is passed in a floating-point register and an integer register, provided the floating-point real is no more than FLEN bits wide and the integer is no more than XLEN bits wide, and at least one floating-point argument register and at least one integer argument register is available. If the struct is passed in this manner, and the integer is narrower than XLEN bits, the remaining bits are unspecified. If the struct is not passed in this manner, then it is passed according to the integer calling convention.

This minor reorganising works for me (and also addresses the grammatical issue)

**Comment by asb** [comment]
Andrew's proposed rewording LGTM.

**Comment by kito-cheng** [comment]
Changes:
- Apply @aswaterman's suggestion

**Comment by kito-cheng** [comment]
Rebase and merge :)

**Pull request merged**
