### PR TITLE
Revert "Add note to mention medlow also called small in certain toolc…

### PR DESCRIPTION
**Pull request by kito-cheng**
…hain implementation"

This reverts commit 621b07468ecbb35c9a0803fe2ee18494ad3e0c52.

### CODE REVIEW

**Comment by luismarques** [comment]
LGTM. (I don't have permission to officially review the PR...)

Personally, I would have preferred to have erred more towards being informative and convenient, leaving such information in, rather than being an "unbiased" specification.

**Comment by asb** [comment]
I have a slight preference for retaining the current explanation. It doesn't look like many of these mappings to toolchain-specific namings are required right now, so it's not like it's a big issue for maintenance.

But it's not a huge issue either way.

**Comment by kito-cheng** [comment]
Counter PR for this https://github.com/riscv-non-isa/riscv-elf-psabi-doc/pull/297

**Comment by jrtc27** [comment]
It’s just a matter of principle to me, this is a specification not a description of implementation quirks. Especially when you don’t need to know the LLVM mappings to use Clang as the standard names do work; the underlying ones just also happen to.

**Comment by asb** [comment]
Personally I'd be in favour of compromising on that suggest principle slightly if there's a major benefit in terms of readability / clarity to the end user. But you make a good point that `-mcmodel=medlow` and `-mcmodel=medany` are accepted by clang (and documented in the `--help` output). So on reflection, this particular case isn't a big deal and I'm happier than I was in going ahead with this revert.

**Comment by kito-cheng** [comment]
Sound like we got consensus here, thanks everyone!

**Pull request merged**
